{
 "title": "Shop Business Metrics",
 "tags": [
  "shop",
  "business",
  "homework"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Available items",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "shop_available_items", "legendFormat": "Available items" }
   ]
  },
  {
   "title": "Stored carts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "shop_stored_carts", "legendFormat": "Stored carts" }
   ]
  },
  {
   "title": "Items created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "shop_items_created_total", "legendFormat": "Created items" }
   ]
  },
  {
   "title": "Carts created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "shop_carts_created_total", "legendFormat": "Created carts" }
   ]
  },
  {
   "title": "Successful shop operations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(shop_cart_additions_total[1m])",
     "legendFormat": "Items added to carts / second"
    },
    {
     "expr": "rate(shop_items_created_total[1m])",
     "legendFormat": "Items created / second"
    },
    {
     "expr": "rate(shop_carts_created_total[1m])",
     "legendFormat": "Carts created / second"
    }
   ]
  }
 ]
}