{
 "title": "Shop API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RPS по ручкам",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 9 },
   "targets": [
    {
     "expr": "sum by (method, handler) (rate(http_requests_total[1m]))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Ответы по статусам",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 9 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 9, "w": 24, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, handler) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}