{
 "title": "Shop API",
 "tags": [
  "shop-api",
  "fastapi"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RPS (всего)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"shop-api\"}[1m]))"
    }
   ]
  },
  {
   "title": "Доля ошибок 5xx",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_requests_total{job=\"shop-api\", status=~\"5..\"}[1m])) / clamp_min(sum(rate(http_requests_total{job=\"shop-api\"}[1m])), 1e-9)"
    }
   ]
  },
  {
   "title": "RPS по ручкам",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, handler) (rate(http_requests_total{job=\"shop-api\"}[1m]))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Размер ответа (среднее, байт)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 20, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_response_size_bytes_sum{job=\"shop-api\"}[1m])) / clamp_min(sum by (handler) (rate(http_response_size_bytes_count{job=\"shop-api\"}[1m])), 1e-9)",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}