# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hw2.hw.grpc_shop import shop_pb2 as shop__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shop_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShopStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateItem = channel.unary_unary(
                '/shop.Shop/CreateItem',
                request_serializer=shop__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=shop__pb2.Item.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/shop.Shop/GetItem',
                request_serializer=shop__pb2.IdRequest.SerializeToString,
                response_deserializer=shop__pb2.Item.FromString,
                _registered_method=True)
        self.GetItems = channel.unary_unary(
                '/shop.Shop/GetItems',
                request_serializer=shop__pb2.GetItemsRequest.SerializeToString,
                response_deserializer=shop__pb2.ItemList.FromString,
                _registered_method=True)
        self.ReplaceItem = channel.unary_unary(
                '/shop.Shop/ReplaceItem',
                request_serializer=shop__pb2.ReplaceItemRequest.SerializeToString,
                response_deserializer=shop__pb2.Item.FromString,
                _registered_method=True)
        self.PatchItem = channel.unary_unary(
                '/shop.Shop/PatchItem',
                request_serializer=shop__pb2.PatchItemRequest.SerializeToString,
                response_deserializer=shop__pb2.Item.FromString,
                _registered_method=True)
        self.DeleteItem = channel.unary_unary(
                '/shop.Shop/DeleteItem',
                request_serializer=shop__pb2.IdRequest.SerializeToString,
                response_deserializer=shop__pb2.Item.FromString,
                _registered_method=True)
        self.CreateCart = channel.unary_unary(
                '/shop.Shop/CreateCart',
                request_serializer=shop__pb2.Empty.SerializeToString,
                response_deserializer=shop__pb2.IdResponse.FromString,
                _registered_method=True)
        self.GetCart = channel.unary_unary(
                '/shop.Shop/GetCart',
                request_serializer=shop__pb2.IdRequest.SerializeToString,
                response_deserializer=shop__pb2.Cart.FromString,
                _registered_method=True)
        self.GetCarts = channel.unary_unary(
                '/shop.Shop/GetCarts',
                request_serializer=shop__pb2.GetCartsRequest.SerializeToString,
                response_deserializer=shop__pb2.CartList.FromString,
                _registered_method=True)
        self.AddItemToCart = channel.unary_unary(
                '/shop.Shop/AddItemToCart',
                request_serializer=shop__pb2.AddItemRequest.SerializeToString,
                response_deserializer=shop__pb2.Cart.FromString,
                _registered_method=True)


class ShopServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplaceItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PatchItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCarts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddItemToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShopServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=shop__pb2.CreateItemRequest.FromString,
                    response_serializer=shop__pb2.Item.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=shop__pb2.IdRequest.FromString,
                    response_serializer=shop__pb2.Item.SerializeToString,
            ),
            'GetItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItems,
                    request_deserializer=shop__pb2.GetItemsRequest.FromString,
                    response_serializer=shop__pb2.ItemList.SerializeToString,
            ),
            'ReplaceItem': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplaceItem,
                    request_deserializer=shop__pb2.ReplaceItemRequest.FromString,
                    response_serializer=shop__pb2.Item.SerializeToString,
            ),
            'PatchItem': grpc.unary_unary_rpc_method_handler(
                    servicer.PatchItem,
                    request_deserializer=shop__pb2.PatchItemRequest.FromString,
                    response_serializer=shop__pb2.Item.SerializeToString,
            ),
            'DeleteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItem,
                    request_deserializer=shop__pb2.IdRequest.FromString,
                    response_serializer=shop__pb2.Item.SerializeToString,
            ),
            'CreateCart': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCart,
                    request_deserializer=shop__pb2.Empty.FromString,
                    response_serializer=shop__pb2.IdResponse.SerializeToString,
            ),
            'GetCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCart,
                    request_deserializer=shop__pb2.IdRequest.FromString,
                    response_serializer=shop__pb2.Cart.SerializeToString,
            ),
            'GetCarts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCarts,
                    request_deserializer=shop__pb2.GetCartsRequest.FromString,
                    response_serializer=shop__pb2.CartList.SerializeToString,
            ),
            'AddItemToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddItemToCart,
                    request_deserializer=shop__pb2.AddItemRequest.FromString,
                    response_serializer=shop__pb2.Cart.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shop.Shop', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shop.Shop', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Shop:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.Shop/CreateItem',
            shop__pb2.CreateItemRequest.SerializeToString,
            shop__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.Shop/GetItem',
            shop__pb2.IdRequest.SerializeToString,
            shop__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.Shop/GetItems',
            shop__pb2.GetItemsRequest.SerializeToString,
            shop__pb2.ItemList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplaceItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.Shop/ReplaceItem',
            shop__pb2.ReplaceItemRequest.SerializeToString,
            shop__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PatchItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.Shop/PatchItem',
            shop__pb2.PatchItemRequest.SerializeToString,
            shop__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.Shop/DeleteItem',
            shop__pb2.IdRequest.SerializeToString,
            shop__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.Shop/CreateCart',
            shop__pb2.Empty.SerializeToString,
            shop__pb2.IdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.Shop/GetCart',
            shop__pb2.IdRequest.SerializeToString,
            shop__pb2.Cart.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCarts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.Shop/GetCarts',
            shop__pb2.GetCartsRequest.SerializeToString,
            shop__pb2.CartList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddItemToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.Shop/AddItemToCart',
            shop__pb2.AddItemRequest.SerializeToString,
            shop__pb2.Cart.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
