CREATE TABLE items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL CONSTRAINT items_price_nonnegative CHECK (price >= 0),
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE carts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE cart_items (
    cart_id INTEGER NOT NULL REFERENCES carts(id),
    item_id INTEGER NOT NULL REFERENCES items(id),
    quantity INTEGER NOT NULL
        CONSTRAINT cart_items_quantity_positive CHECK (quantity > 0),
    PRIMARY KEY (cart_id, item_id)
);
